-- DDL generated by Postico 1.5.19
-- Not all database features are supported. Do not use for backup.

-- Table Definition ----------------------------------------------

CREATE TABLE tasklist (
    id integer DEFAULT nextval('tasklist_id_seq1'::regclass) PRIMARY KEY,
    task text,
    done boolean DEFAULT false
);

-- Indices -------------------------------------------------------

CREATE UNIQUE INDEX tasklist_pkey ON tasklist(id int4_ops);
